version: "3.9"

services:
  mcs:
    build:
      context: .
      #dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_PATH=/var/lib/mcs/medical_coder.db
      - WORKSPACE_DIR="agent_workspace"
    volumes:
      - mcs-data:/var/lib/mcs
#      - mcs-data:/opt/mcs
    restart: always

volumes:
  mcs-data:
    driver: local
